### ISSUE TITLE
Request for Assistance with Python Script for Downloading Images

### ISSUE THREAD

**Issue by Kajal4414** [anburocky3/Ragalahari-downloader#3]
Unfortunately, the script does not seem to be functioning properly, and I am unable to download the images as intended. I have tried troubleshooting the issue on my end, but have not been able to resolve it.

**Comment by anburocky3** [comment]
What error do you face btw?

Have you checked this article: https://anbuselvanrocky.medium.com/how-to-download-ultra-hd-images-from-ragalahari-com-site-b8458ddffffd

**Comment by Kajal4414** [comment]
> What error do you face btw?
> 
> Have you checked this article: https://anbuselvanrocky.medium.com/how-to-download-ultra-hd-images-from-ragalahari-com-site-b8458ddffffd

Yes, I checked this article

**see this**
```bash
Enter your URL Path of the images: https://www.ragalahari.com/actor/171464/allu-arjun-at-honer-richmont-launch.aspx
Enter your file_name: arjun
Folder name: aj
How much image you want me to download? (Default: 100): 15
Searching files. . . . .
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Sakshi\Desktop\Ragalahari-downloader\downloader.py", line 140, in main
    checkFileExist(file_path, file_name, cycle)
  File "c:\Users\Sakshi\Desktop\Ragalahari-downloader\downloader.py", line 41, in checkFileExist
    if exists(file_path, file_name % i):
                         ~~~~~~~~~~^~~
TypeError: not all arguments converted during string formatting
PS C:\Users\Sakshi\Desktop\Ragalahari-downloader>
```

**Comment by anburocky3** [comment]
> If your URL is this: https://www.ragalahari.com/actor/171464/allu-arjun-at-honer-richmont-launch.aspx

The direct image URL is: https://szcdn.ragalahari.com/aug2022/hd/allu-arjun-honer-richmont-launch/allu-arjun-honer-richmont-launch1t.jpg 

So you have to replace the repeating number. Which is `richmont-launch1t.jpg`

1. Enter your URL path of the images: https://szcdn.ragalahari.com/aug2022/hd/allu-arjun-honer-richmont-launch/
(We should only enter the image path, not the full image url, it will autofetch)

2. Enter the filename: `allu-arjun-honer-richmont-launch%dt.jpg`

(Replace the number, you like to increment. That file will be checked and downloaded.)

3. Folder name: `Allu-Arjun`

(This will help to organize your gallery.)

4. How much image you want me to download? `15`

(This will download 15 images from the above URL path)

**Comment by anburocky3** [comment]
@sakshiagrwal Check with the above inputs. If you still face problem, revert back with the problem with screenshot.

**Comment by Kajal4414** [comment]
> @sakshiagrwal Check with the above inputs. If you still face problem, revert back with the problem with screenshot.

Thank you for your help! I had an issue earlier, but it's been resolved now. Your assistance was greatly appreciated. Thank you again for your prompt response!
