### ISSUE TITLE
NameError: name requests is not defined.

### ISSUE THREAD

**Issue by arijit64** [anburocky3/Ragalahari-downloader#5]
![Screenshot_20240222-161209](https://github.com/anburocky3/Ragalahari-downloader/assets/108784413/0b4ab9b7-34d5-4ff4-a31d-aed6d04113d1)

I was trying to download some images from this link: https://www.ragalahari.com/actor/164289/stylish-star-allu-arjun-photos.aspx
But I got this error `NameError: name requests is not defined` 
I followed every steps from https://anbuselvanrocky.medium.com/how-to-download-ultra-hd-images-from-ragalahari-com-site-b8458ddffffd

As you can see in the screenshot, I entered
    1. Enter your URL path of the images: `https://starzone.ragalahari.com/july2018/starzone/allu-arjun-geetha-govindam/` 
    2. Enter the file_name: `allu-arjun-geetha-govindam%d.jpg` 
    3. Folder name: `allu-arjun-geetha-govindam`
    4. How much image you want me to download? `50`

What am I doing wrong here? I need some assistance.

**Comment by anburocky3** [comment]
Can you try this in PC/Laptop? Not sure, will it work on Mobile terminals.

Try to run this on PC/Laptop

**Comment by arijit64** [comment]
I tested the script on my PC and it's working flawlessly. I truly appreciate your prompt assistance, thank you!
